version: '2'

services:
  headbanger:
    build: .
    ports:
      - 8080
    volumes:
      - log:/app/log/
    links:
      - redis
      - postgres
      - neo4j
    depends_on:
      - redis
      - postgres
      - neo4j
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - redis:/var/lib/redis/data
  postgres:
    image: postgres:9.5
    ports:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
  neo4j:
    image: neo4j:3.0
    ports:
      - 7474
    volumes:
      - neo4j:/var/lib/neo4j/data

volumes:
  log: {}
  redis: {}
  postgres: {}
  neo4j: {}