version: '2'

services:
  app:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - assets:/app/assets/public/
    links:
      - redis
      - postgres
      - neo4j
    depends_on:
      - redis
      - postgres
      - neo4j
      - musicbrainz
    env_file:
      - headbanger.dev.env
  redis:
    image: redis:alpine
    ports:
      - "6379"
    volumes:
      - redis:/var/lib/redis/data
  postgres:
    image: postgres:9.6
    ports:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  neo4j:
    image: neo4j:3.0
    ports:
      - "7474"
    volumes:
      - neo4j:/var/lib/neo4j/data
  musicbrainz:
    image: linuxserver/musicbrainz
    ports:
      - "5000"
    volumes:
      - mb_config:/config
      - mb_data:/data
    env_file:
      - musicbrainz.env

volumes:
  redis: {}
  postgres: {}
  neo4j: {}
  assets: {}
  mb_config: {}
  mb_data: {}