version: '2'

services:
  app:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - log:/app/log/
    links:
      - redis
      - postgres
      - neo4j
    depends_on:
      - redis
      - postgres
      - neo4j
    env_file:
      - .env
  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis:/var/lib/redis/data
  postgres:
    image: postgres:9.6
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  neo4j:
    image: neo4j:3.0
    ports:
      - "127.0.0.1:7474:7474"
    volumes:
      - neo4j:/var/lib/neo4j/data

volumes:
  log: {}
  redis: {}
  postgres: {}
  neo4j: {}