default: &default
  type: server_db
  url: <%= "http://#{ENV['NEO4J_USER']}:#{ENV['NEO4J_PASS']}@#{ENV['NEO4J_HOST']}:#{ENV['NEO4J_PORT']}" %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
